---
abstract: 'Wrapper modules & scripts for DTA XML corpus tokenization'
author:
  - 'Bryan Jurish <moocow@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.1002, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DTA-TokWrap
no_index:
  directory:
    - t
    - inc
requires:
  Algorithm::BinarySearch::Vec: '0.05'
  Cwd: '0'
  Encode: '0'
  Env::Path: '0.18'
  File::Basename: '0'
  Getopt::Long: '0'
  Log::Log4perl: '1.2'
  Pod::Usage: '0'
  Test::More: '0'
  Time::HiRes: '1.9711'
  XML::LibXML: '0'
  XML::LibXSLT: '0'
  XML::Parser: '0'
version: 0.86-pre1
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
